# Generated by Django 3.2 on 2021-04-11 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='ancient', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugs.bug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
