# Generated by Django 3.2 on 2021-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20210411_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
